[package]
name = "poem_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = "1.3.55"
poem-openapi = "2.0.26"
tokio = { version = "1.17.0", features = ["full"] }